### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [EmersonNog/plugin-flood-path-finder-qgis#1]
# problem

Please remove https://github.com/EmersonNog/plugin-flood-path-finder-qgis/tree/main/__pycache__, it's auto generated on install
Also adjust the metadata.txt to remove links from your Instagram profile, ideally everything should be links on this repo. When you have changed the metadata.txt please update the plugin from the repository

**Comment by EmersonNog** [comment]
Problems resolved, files are now updated.
